// ─── Config CRUD — delegated to JSON-backed config store ──────────────────────
export {
  listLmConnections,
  upsertLmConnection,
  deleteLmConnection,
  listModelConfigs,
  upsertModelConfig,
  deleteModelConfig,
  listMcpServerProfiles,
  upsertMcpServerProfile,
  deleteMcpServerProfile,
  getSessionCreationDefaults,
  upsertSessionCreationDefaults,
  type SessionCreationDefaults,
  ConfigFileError,
} from "../config/configStore.js";

export type { ActiveSessionInfo } from "./repositoryRuntime.js";
export {
  insertStepRecord,
  updateStepRecord,
  createSessionRecord,
  getSessionRecord,
  updateSessionRecord,
  updateSessionAnalysisState,
  deleteSessionRecord,
  listSessionRecords,
  listSessionSummaries,
  listChildSessionSummaries,
  listAllSessionSummaries,
  findActiveSession,
  recoverInterruptedState,
  getStepRecord,
  listStepRecordsBySession,
  getNextChildIndex,
  insertTurnRecord,
  updateTurnRecord,
  getTurnRecord,
  listTurnRecordsBySession,
  insertRoundRecord,
  updateRoundRecord,
  getRoundRecord,
  listRoundRecordsBySession,
  insertPartRecord,
  updatePartRecord,
  getPartRecord,
  listPartRecordsBySession,
  insertRawExchangeRecord,
  listRawExchangeRecordsBySession,
  getNextTurnNumber,
  getNextPartOrdinal,
  getNextRoundPartSequence,
  getNextPreludePartSequence,
} from "./repositoryRuntime.js";

// ─── Benchmark CRUD ───────────────────────────────────────────────────────────
export {
  createBenchmark,
  getBenchmark,
  listBenchmarks,
  updateBenchmark,
  deleteBenchmark,
  createBenchmarkCase,
  getBenchmarkCase,
  listBenchmarkCases,
  updateBenchmarkCase,
  deleteBenchmarkCase,
  createBenchmarkRun,
  getBenchmarkRun,
  listBenchmarkRuns,
  updateBenchmarkRun,
  deleteBenchmarkRun,
} from "./benchmarkRepository.js";
